name: Code check

on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [master, "release/*", "future/*"]
  pull_request:
    branches: [master, "release/*", "future/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  mypy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Note: This uses an internal pip API and may not always work
    # https://github.com/actions/cache/blob/master/examples.md#multiple-oss-in-a-workflow
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/base.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install torch==1.11 --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
        python ./requirements/adjust-versions.py requirements/extra.txt
        pip install '.[dev]'
        pip list

    - name: Type check
      run: mypy src/ --install-types --non-interactive
